### ISSUE TITLE
Unaprijediti SRS Dokument - Funkcionalnost Proizvoda - Dio I

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#10]
### _Navedena poglavlja dodati (sa tekstom) unutar kreiranog SRS dokumenta._

**Broj Sekcije:** 2.
**Naziv Sekcije:** Opis

**2.2.1.** Funkcionalnost Web Aplikacije
- Registracija/Login
- Pregled sadržaja
- Online rezervacija
- Pregled izvještaja
- Administracija sistema

**2.2.2.** Funkcionalnost Desktop Aplikacije
- Upravljanje sistema za posluživanje
- Izdavanje računa
- SMS/Viber Rezervacija
- Pregled izvještaja
- Administracija sistema

**Comment by msosic1** [comment]
Dodana navedena poglavlja.
