### ISSUE TITLE
Unaprijedi SRS Dokument - Konkretni Zahtjevi - Dio II

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#12]
### _Navedena poglavlja dodati (sa tekstom) unutar kreiranog SRS dokumenta._

**Broj Sekcije:** 3.
**Naziv Sekcije:** Konkretni Zahtjevi

**3.3.** Nefunkcionalni zahtjevi
- **3.3.1.** Upotrebljivost
- **3.3.2.** Performanse

**3.4.** Atributi kvalitete softvera

- **3.4.1.** Pouzdanost
- **3.4.2.** Dostupnost
- **3.4.3.** Sigurnost
- **3.4.4.** Održavanje sistema
- **3.4.5.** Poratabilnost

**Comment by ikulovac1** [comment]
**3.3 Nefunkcionalni zahtjevi**
3.3.1. Upotrebljivost
Dizajn grafičkog interfejsa, kao i samog sistema, trebao bi da bude što više prilagođen korisniku kako bi se mogao što jednostavnije i intuitivnije koristiti, a da pri tome sve funkcionalnost sistema vezane za tog korisnika budu dostupne.
Što jednostavniji unos podataka u sistem omogućio bi uposlenicima efikasniji rad. Prema navedenom, imamo sljedece nefunkcionalne zahtjeve vezane za upotrebljivost sistema:
NFZ 1. Dizajn grafičkog interfejsa za korisnike sistema treba da bude što jednostavniji za upotrebu. 
(Pošto je u pitanju NFZ kojem nije moguće definisati jasnu validaciju jednostavnosti, jer zavisi od subjektivnog dojma korisnika, sistem će se smatrati jednostavnim ako 70% korisnika sistema bude izjasnilo da je sistem za njih jednostavan).
NFZ 2. Dizajn grafičkog interfejsa za korisnike sistema treba da bude što intuitivniji. 
(Pošto je u pitanju NFZ kojem nije moguće definisati jasnu validaciju jednostavnosti, jer zavisi od subjektivnog dojma korisnika, sistem ce se smatrati intuitivnim ako 70% korisnika sistema bude izjasnilo da je sistem za njih intuitivan).
NFZ 3. Dizajn grafičkog interfejsa za korisnike sistema treba da nudi sve funkcionalnosti koje su vezane za korisničku grupu. Pod ovim podrazumjevamo da su korisničkoj grupi dodjeljene samo one funkcionalnosti koje su potrebne istim, da ne postoje funkcionalnosti koje fale, te da ne postoje funkcionalnosti u grupi korisnika koje ne trebaju, po specifikaciji, pripadati toj grupi.
NFZ 4. Dizajn grafičkog interfejsa treba omogućiti efikasan unos podataka korisnicima.

3.3.2. Performanse
Zbog samog tipa poslovanja, a i trenutne veličine poslovne organizacije, ne očekuje se veliko opteredenje sistema. Ne očekuje se da de ovaj sistem imati preko 50 istovremenih zahtjeva u jednom danu. Međutim, da dobre performanse ne bi bile upitne, naš sistem de podržati i mnogo veda opteredenja. Iz ovoga imamo sljedede:
NFZ 5 Sistem de omoguditi rad najmanje 10 korisnika sistema (radnika,običnih korisnika ili administracije) istovremeno .
NFZ 6. Sistem de omoguditi odgovor na najmanje 5 zahtjeva po sekundi.


**3.4. Atributi kvalitete sistema**
Web aplikacija de biti dostupna 24 sata na dan 7 dana u sedmici. Kao što smo prethodno naveli, ne očekuje se veliko opteredenje sistema, pa se pouzdanost sistema ogleda u pouzdanosti servera i baze podataka. Također, sigurnosne kopije i srednje vrijeme između kvarova su od velikog značaja na pouzdanostsistema,pademoovdjepratitidirektiveISO27002:2005 standarda.Premanavedenom, imamo sljedede nefunkcionalne zahtjeve vezane za atribute kvalitete sistema:

3.4.1. Pouzdanost

NFZ 7. Web aplikacija biti de dostupna 24 sata na dan, 7 dana u sedmici.
NFZ 8. Srednje vrijeme između kvaraova ne bi trebalo biti krace od 3 mjeseca.
NFZ 9. Sistem ce omoguciti automatsko spašavanje sigurnosnih kopija svaki dan nakon završetka radnog vremena, kao i omoguciti spašavanje sigurnosnih kopija na zahtjev korisnika.

3.4.2. Dostupnost
NFZ 10. Sistem ce imati dostupnost 99.9% vremena
NFZ 11. Testiranje i daljnji razvoj sistema nece imati uticaj na rad sistema

3.4.3. Sigurnost
NFZ 12. Testiranje i daljnji razvoj sistema nece imati uticaj na sigurnost sistema
NFZ 13. Sistem ce omoguditi dodavanje i brisanje korsinika sistema od strane nadležne osobe
NFZ 14. Sistem ce omoguditi određivanje privilegija korisnika za rad u sistemu od strane nadležne osobe
NFZ 15. Sisitem ce zahtjevati od korisnika prijavu na sistem unošenjem korisničkog imena i šifre prije nego pristupi funkcionalnostimasistema
NFZ 16. Sistem ce dozvoliti korisniku pristup samo onim funkcionalnostima sistema za koje ima privilegije
NFZ 17. Sistem nece pohranjivati šifru korisnika, ved njenu hash vrijednost
NFZ 18. Sistem ce držati zapise (logove) o svim izvršenim transakcij ama
NFZ 19. Sistem ce dozvoliti pristup Web i desktop aplikaciji samo koristedi sigurnu konekciju
NFZ 20. Sistem ce automatski prekinuti sve neaktivne sesije nakon određenog vremenskog perioda

3.4.4. Održavanje sistema
NFZ 21. Bit ce omogucena zamjena ili nadogradnja hardvera bez prekida rada sistema
NFZ 22. Bit ce omogucena nadogradnja softvera bez prekida rada sistema

3.4.5. Portabilnost
NFZ 23. Sistem ce ga biti moguce koristiti na svakom operativnom sistemu uz predpostavku da je instaliran neki od internet pretraživača kao što su Google Chrome ili Mozilla Firefox
