### ISSUE TITLE
Unaprijedii i Očistiti SRS Dokument - Poglavlje 2

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#16]
### _Navedena poglavlja treba ispraviti  i/ili nadopuniti._

**Broj Sekcije:** 1.
**Naziv Sekcije:** Reference

**Zahtjevi:**
- Morate u poglavlju 1.5 Reference imati punu korektnu referencu svakog korištenog dokumenta: naslov, izdavač, godina izdanja, ako je dio nekog grupnog izdanja /časopis, knjiga/ podaci o tom grupnom izdanju, npr. za zakone Službeni list i eventualno link za online preuzimanje.
- U poglavlju 2.4 imate "Ograničenja vezana za zagonsku regulativu potrošača" - koji je ovo konkretno zakon? U kojem izdanju kojih službenih novina je objavljen? Ovdje su koliko vidim samo citirani članovi zakona, a morate prodiskutovati kako se svaki od tih članova odnosi na vaš sistem. Postoje li neki pravilnici za oblast kinematografije?
- Poglavlje 2.5 Pretpostavke i zavisnosti je dosta šturo napisano.

**Savjeti:**
- Dodati detalje sa referenci, tačnije dodati porijeklo, te dodati nekoliko (po mogućnosti) zakona striktno vezanih za filmove. (Važi i za 2.4)
- Prošitit poglavlje 2.5 sa barem još nekoliko primjera.

**Obavezno ispraviti gramatičke greške za navedene pasuse kao i za dio teksta rađen na prošlom projektnom zadatku.**

**Comment by eskalonjic2** [comment]
Završeno.
