### ISSUE TITLE
Kreirati lokalnu Web Aplikaciju

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#5]
**Ime zadatka:** Kreirati lokalnu Web Aplikaciju

**Opis zadatka:** Kreirati lokalnu React JS aplikaciju te instalirati neophodne module koji su dogovoreni na sastanku, ne pushati na repozitorij, istažiti koji paketi su potrebni za ovakav vid aplikacije, pronaći nekoliko dobrih primjera dizajna. Obavezno instalirati ant-d UI Library i istražiti njegove mogućnosti i komponente zbog lakše i brže implementacije.

**UML dijagram:** _Nije potreban za sada_

**Comment by eskalonjic2** [comment]
Završeno.
