### ISSUE TITLE
Kreirati JavaFX Aplikaciju za radnike

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#6]
**Ime zadatka:** Kreirati JavaFX Aplikaciju za radnike

**Opis zadatka:** Kreirati lokalnu Java FX aplikaciju u kojoj će se razvijati interfejs za radnike, dodati neophone Maven pakete, pronaći primjere dobrog dizajna te razmisliti o arhitekturi ove aplikacije.

**UML dijagram:** _Nije potreban za sada_

**Comment by Avujcic1** [comment]
Zavrseno
