### ISSUE TITLE
Kreirati JavaFX Aplikaciju za Korisnike

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#7]
**Ime zadatka:** Kreirati JavaFX Aplikaciju namjenjena za korisnike

**Opis zadatka:** Kreirati JavaFX Aplikaciju namjenjena za korisnike, aplikacija će biti instalirana na touch panelima u holu te će služiti za rezervacije, takođe instalirati neophodne Maven pakete, istražiti najbolje metode za razvoj ovakve aplikacije te pronaći nekoliko primjera dobrog dizajna

**UML dijagram:** _Nije potreban za sada_

**Comment by msosic1** [comment]
Zavrseno!

**Comment by msosic1** [comment]
Zavrseno!
