### ISSUE TITLE
Unaprijediti SRS dokument - Opis - Dio I

### ISSUE THREAD

**Issue by almulalic** [almulalic/nrs20-tim7#8]
### _Navedena poglavlja dodati (sa tekstom) unutar kreiranog SRS dokumenta._

**Broj Sekcije:** 2.
**Naziv Sekcije:** Prespektiva Proizvoda
**Naziv Podsekcije:** Prespektiva Proizvoda, Ograničenja, Pretpostavke, Planiranje zahtjeva

**2.1.** Prespektiva Proizvoda
- Korisnički web interfejs 
- Interfejs za uposlenike kina
- Interfejs za menadžment
- Interfejs za samousluživanje
- Hardverski i komunikacijski interfejs
- Softverski Interfejs

**2.4.** Ograničenja
**2.5.** Pretpostavke
**2.6.** Planiranje zahtjeva

**Comment by eskalonjic2** [comment]
Završio
